apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-demo
  name: flask-demo
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd_deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-demo
    spec:
      containers:
      - image: tosicky/flask_demo:v1
        name: flask-demo
        imagePullPolicy: Always
        resources: {}
      imagePullSecrets:
      - name: argocdcred
status: {}
